In [1]:
import numpy as np
#陣列運算
a=np.array([1,3,5,7,9])
a*=10
a

array([10, 30, 50, 70, 90])

In [2]:
a=np.array([1,3,5,7,9])
b=np.array([2,4,6,8,10])
#陣列運算
a+b

array([ 3,  7, 11, 15, 19])

In [6]:
#2維ndarray
arr=np.array([[1,3,5],[2,4,6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [9]:
np.random.rand()
np.random.rand(30,4)

array([[0.36398348, 0.18418836, 0.34367481, 0.70994024],
       [0.28530625, 0.92238624, 0.84822023, 0.20681952],
       [0.35713167, 0.18100708, 0.4581195 , 0.20717343],
       [0.02703575, 0.7380499 , 0.77592887, 0.76604457],
       [0.78442953, 0.88617029, 0.69345087, 0.51332297],
       [0.43109719, 0.31150741, 0.8768121 , 0.09095299],
       [0.51182961, 0.5744157 , 0.67681008, 0.31427183],
       [0.52599104, 0.69767376, 0.86638727, 0.70502237],
       [0.38645368, 0.83097181, 0.57999297, 0.92919697],
       [0.03353797, 0.76190526, 0.09905973, 0.99987678],
       [0.61837071, 0.71440594, 0.01805981, 0.8180206 ],
       [0.60386628, 0.27096013, 0.55800778, 0.54455455],
       [0.87914489, 0.17758964, 0.11857308, 0.65701771],
       [0.12320744, 0.81968975, 0.84233392, 0.54203469],
       [0.44221418, 0.46764054, 0.14237641, 0.42353946],
       [0.03857213, 0.07643158, 0.70566355, 0.4656744 ],
       [0.03361273, 0.85031505, 0.39481321, 0.22270628],
       [0.75458446, 0.72313543,

In [11]:
scores=np.random.randint(50,101,size=(50,5))
scores

array([[ 79,  69,  90,  88,  77],
       [ 62,  89,  75,  55,  66],
       [ 79,  87,  88,  98,  85],
       [ 77,  76,  80,  51,  83],
       [ 87,  93,  55,  85,  97],
       [ 91,  67,  95,  92,  68],
       [ 79,  98,  95,  94,  81],
       [ 66,  53,  63,  64,  79],
       [ 53, 100,  84,  77,  80],
       [ 51,  65,  50,  58,  79],
       [ 70,  82,  76,  63,  75],
       [ 79,  61,  60,  97,  95],
       [ 78,  52,  64,  86,  83],
       [ 63,  91,  74,  51,  63],
       [ 59,  99,  72,  65,  88],
       [ 74,  54,  86,  63,  73],
       [ 65,  84,  79,  64,  52],
       [ 74,  80,  56,  83,  82],
       [ 68,  78,  91,  55,  91],
       [ 88,  99,  80,  50,  67],
       [ 86,  91,  61,  53,  60],
       [ 85,  82,  93,  92,  89],
       [ 77,  92,  81,  91,  73],
       [100,  52,  60,  52,  66],
       [ 60,  75,  70,  66,  58],
       [ 73,  53,  85,  81,  92],
       [ 71,  53,  91,  99,  55],
       [ 65,  75,  62,  69,  86],
       [ 81,  85,  75,  81,  68],
       [ 59,  