In [ ]:
import numpy as np
arr=np.arange(10)*10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#索引(index)
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([ 0, 10, 20, 30, 40])

In [5]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 58,  81,  96,  57,  79],
       [ 92,  71,  63,  65,  53],
       [ 65,  59,  94,  77,  73],
       [ 51,  60,  60,  99,  95],
       [ 92,  68,  58,  85,  86],
       [ 66,  96,  71,  55,  57],
       [ 85,  52,  66,  86,  90],
       [ 81,  65,  55,  86,  52],
       [ 58,  57,  80,  57,  88],
       [ 76,  57,  58,  67,  90],
       [ 67,  74,  52,  98,  68],
       [ 51,  87,  82,  53,  71],
       [ 68,  61,  66,  53,  97],
       [ 56,  62,  70,  60,  73],
       [ 93,  67,  74,  50,  74],
       [ 97, 100,  80,  53,  96],
       [ 71,  94,  98,  61,  86],
       [ 93,  53,  64,  72,  67],
       [ 93,  71,  83,  87,  95],
       [ 99,  90,  87,  60,  90],
       [ 85,  64,  95,  74,  92],
       [ 55,  77,  71,  58,  50],
       [ 53,  82,  72,  65,  85],
       [ 65,  64,  67,  86,  72],
       [ 80,  93,  78,  78,  94],
       [ 98,  81,  69,  89,  82],
       [ 75,  85,  59,  79,  98],
       [ 53,  69,  76,  87,  98],
       [ 75, 100,  92,  73,  79],
       [ 81,  

In [8]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1,5)

array([[58, 81, 96, 57, 79]])

In [12]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[58, 81, 96],
       [92, 71, 63],
       [65, 59, 94],
       [51, 60, 60],
       [92, 68, 58]])

In [9]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 96,  63,  94,  60,  58,  71,  66,  55,  80,  58,  52,  82,  66,
        70,  74,  80,  98,  64,  83,  87,  95,  71,  72,  67,  78,  69,
        59,  76,  92,  94,  88,  98, 100,  74,  50,  92,  74,  60,  90,
        57,  65,  82,  84,  73,  71,  58,  71,  86,  53,  50])

In [10]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([371, 344, 368, 365, 389, 345, 379, 339, 340, 348, 359, 344, 345,
       321, 358, 426, 410, 349, 429, 426, 410, 311, 357, 354, 423, 419,
       396, 383, 419, 394, 332, 397, 394, 346, 328, 376, 366, 402, 389,
       340, 325, 432, 443, 394, 367, 379, 381, 364, 353, 384])

In [11]:
total/5

array([74.2, 68.8, 73.6, 73. , 77.8, 69. , 75.8, 67.8, 68. , 69.6, 71.8,
       68.8, 69. , 64.2, 71.6, 85.2, 82. , 69.8, 85.8, 85.2, 82. , 62.2,
       71.4, 70.8, 84.6, 83.8, 79.2, 76.6, 83.8, 78.8, 66.4, 79.4, 78.8,
       69.2, 65.6, 75.2, 73.2, 80.4, 77.8, 68. , 65. , 86.4, 88.6, 78.8,
       73.4, 75.8, 76.2, 72.8, 70.6, 76.8])

In [15]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([74.2, 68.8, 73.6, 73. , 77.8, 69. , 75.8, 67.8, 68. , 69.6, 71.8,
       68.8, 69. , 64.2, 71.6, 85.2, 82. , 69.8, 85.8, 85.2, 82. , 62.2,
       71.4, 70.8, 84.6, 83.8, 79.2, 76.6, 83.8, 78.8, 66.4, 79.4, 78.8,
       69.2, 65.6, 75.2, 73.2, 80.4, 77.8, 68. , 65. , 86.4, 88.6, 78.8,
       73.4, 75.8, 76.2, 72.8, 70.6, 76.8])

In [18]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)


array([74.2, 68.8, 73.6, 73. , 77.8, 69. , 75.8, 67.8, 68. , 69.6, 71.8,
       68.8, 69. , 64.2, 71.6, 85.2, 82. , 69.8, 85.8, 85.2, 82. , 62.2,
       71.4, 70.8, 84.6, 83.8, 79.2, 76.6, 83.8, 78.8, 66.4, 79.4, 78.8,
       69.2, 65.6, 75.2, 73.2, 80.4, 77.8, 68. , 65. , 86.4, 88.6, 78.8,
       73.4, 75.8, 76.2, 72.8, 70.6, 76.8])