In [1]:
import numpy as np
#陣列運算
a=np.array([1,3,5,7,9])
a*=10
a

array([10, 30, 50, 70, 90])

In [2]:
a=np.array([1,3,5,7,9])
b=np.array([2,4,6,8,10])
#陣列運算
a+b

array([ 3,  7, 11, 15, 19])

In [6]:
#2維ndarray
arr=np.array([[1,3,5],[2,4,6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [9]:
np.random.rand()
np.random.rand(30,4)

array([[0.36398348, 0.18418836, 0.34367481, 0.70994024],
       [0.28530625, 0.92238624, 0.84822023, 0.20681952],
       [0.35713167, 0.18100708, 0.4581195 , 0.20717343],
       [0.02703575, 0.7380499 , 0.77592887, 0.76604457],
       [0.78442953, 0.88617029, 0.69345087, 0.51332297],
       [0.43109719, 0.31150741, 0.8768121 , 0.09095299],
       [0.51182961, 0.5744157 , 0.67681008, 0.31427183],
       [0.52599104, 0.69767376, 0.86638727, 0.70502237],
       [0.38645368, 0.83097181, 0.57999297, 0.92919697],
       [0.03353797, 0.76190526, 0.09905973, 0.99987678],
       [0.61837071, 0.71440594, 0.01805981, 0.8180206 ],
       [0.60386628, 0.27096013, 0.55800778, 0.54455455],
       [0.87914489, 0.17758964, 0.11857308, 0.65701771],
       [0.12320744, 0.81968975, 0.84233392, 0.54203469],
       [0.44221418, 0.46764054, 0.14237641, 0.42353946],
       [0.03857213, 0.07643158, 0.70566355, 0.4656744 ],
       [0.03361273, 0.85031505, 0.39481321, 0.22270628],
       [0.75458446, 0.72313543,

In [10]:
np.random.randint(50,101,size=(50,5))

array([[ 79,  77,  65,  76,  70],
       [ 70,  51,  90,  88,  57],
       [ 87,  53,  83,  80,  54],
       [ 82,  82,  61,  56,  63],
       [ 51,  72,  90,  99,  54],
       [ 56,  66,  94,  72,  74],
       [ 56,  78,  83,  52,  63],
       [ 62,  89,  78,  60,  51],
       [ 76,  66,  79,  98,  85],
       [ 73,  93,  64,  96,  69],
       [ 92,  95,  77,  88,  52],
       [ 74,  57,  72,  52,  68],
       [ 50,  72,  53,  55,  71],
       [ 79,  88,  70,  65,  88],
       [ 71,  52,  72,  56,  87],
       [ 60,  97,  74,  70,  83],
       [ 73,  82,  87,  76,  58],
       [ 57,  83,  58,  56,  70],
       [ 52,  84,  86,  60,  86],
       [ 89,  60,  85,  79,  62],
       [ 81,  72,  62,  80,  53],
       [ 91,  57,  81,  85,  53],
       [ 87,  68,  50,  89,  66],
       [ 97,  56,  89,  80,  75],
       [ 72,  69,  70,  93,  86],
       [ 61,  89,  59,  91,  85],
       [ 86,  86,  98,  55,  94],
       [ 76, 100,  69,  98,  65],
       [ 54,  96,  81,  75,  61],
       [ 79, 1